version: "3"
services: 
 node-app: 
  container_name: test-docker
  build: 
   context: .
   target: production
  ports:
    - 4000:4000
  environment:
    - NODE_ENV=production
  env_file: 
    - ./.env
 


