version: "3"
services: 
 node-app: 
  container_name: test-docker
  image: beltagyy/test-docker
  build: .
  volumes:
     - ./src:/app/src:ro
  # ports:
  #   - 4000:4000
  env_file: 
    - ./.env
  depends_on:
    - postgres
    - redis
#  mongo:

#     image: mongo
#     restart: always
#     volumes:
#       - mongo-db:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#     depends_on:
#      - mongo
 redis: 
   image: redis

 nginx:
  image: nginx:stable-alpine
  volumes:
   - ./templates:/etc/nginx/templates
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  depends_on:
   - node-app 

 postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: example
    volumes:
      -   postgres-db:/var/lib/postgresql/data
 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080
volumes:
  mongo-db:  
  postgres-db:
